### ISSUE TITLE
Slicing error in Bim_d1.py for Python 3.6.0

### ISSUE THREAD

**Issue by pcerdam** [dipaco/balu-python#18]
Hello,

I am trying to get the basic intensity features of an image, but am not able to due to a non-Int type error on the indexes that are used to copy Y0 to Y. Changing:

`c = (m-1)/2`

to

`c=(m-1)//2`

On line 39 seems to work, but maybe it should be done just before line 57, instead. 

Can anyone confirm that this is indeed a bug? Thanks in advance.

**Comment by dipaco** [comment]
Sorry for the superlate response. I haven't got time to work on this project. It is indeed a bug and it is now corrected. Also I just removed mahotas dependency. It caused no more than troubles.

Thanks.
